#!/bin/bash
if [ $# -lt 1 ]; then
	echo "Use $0 <0 or 1>"
	exit 1
fi

folder="$1"
if [ ! -d "$dir" ]; then
   dir="files-$1/var/log/*/"
fi

cli=""
for i in $(ls $folder); do
	cli="$cli <( echo '==== $folder/$i' ) $folder$i"
done 

eval "cat $cli | less"

