#!/bin/bash
if [ $# -lt 1 ]; then
	echo "Use $0 <folder | 'X' in 'files-X' >"
	exit 1
fi

dir="$1"
if ! [ -d "$dir" ]; then
   dir="files-$1/var/log/*/"
fi

echo "Directory: {$dir}"
cli=""
for i in $(ls $dir); do
	cli="$cli <( echo '==== $i' ) $dir$i"
done 

#echo -e "Command:\n$cli"
eval "cat $cli |less"

